Name = input("What is your name?")
print("you entered:")
print(Name)
Age = input("How old are you?")
print("you entered:")
print(Age)
favorite_food = input("What is your favorite food?")
print("you entered:")
print(favorite_food)
favorite_color = input("What is your favorite color?")
print("you entered:")
print(favorite_color)
favorite_movie = input("What is your favorite movie?")
print("you entered:")
print(favorite_movie)

print("processing your lame answers and giving you second degree burns")
print(f"\n")
print(f"Alright, you are {Name}, right? Such a weird name.")
print(f"you're {Age}? Shouldn't you have a car?")
print(f"{favorite_food}, really? So childish")
print(f"your favorite movie is {favorite_movie}? Don't little kids watch that?")
print(f"{favorite_color}? Such a plain color.")
print(f"\n")
print("Thanks for sharing your boring interests. your data isn't safe with me.")